In [3]:
import numpy as np
print(np.__version__ )

2.3.3


In [13]:
def matriz_de_rotacion(theta:float) -> np.ndarray:
    return np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta),  np.cos(theta)]])

$R(\theta)= \begin{bmatrix} 
\cos\theta & \sin\theta\\ 
-\sin\theta & \cos\theta 
\end{bmatrix}$ 

In [18]:
theta = np.pi / 5
r = matriz_de_rotacion(theta)
print(r)

r_t = np.transpose(r)
print(r_t)

r_i = np.linalg.inv(r)
print(r_i)

r_rt = np.dot(r_t, r)
print(r_rt)

print(np.allclose(np.dot(r, r_t), np.eye(2)))  # De

[[ 0.80901699 -0.58778525]
 [ 0.58778525  0.80901699]]
[[ 0.80901699  0.58778525]
 [-0.58778525  0.80901699]]
[[ 0.80901699  0.58778525]
 [-0.58778525  0.80901699]]
[[ 1.00000000e+00 -1.26599665e-17]
 [-1.26599665e-17  1.00000000e+00]]
True
